# argo-cd/applications/monitoring.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    component: observability
    team: ml-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ml-platform
  source:
    repoURL: https://github.com/your-org/mlops-drift-detection-platform.git
    targetRevision: main
    path: kubernetes/components/monitoring
    plugin:
      name: kustomize
    directory:
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true